const { withXcodeProject } = require('@expo/config-plugins');

/**
 * Config plugin that pins the iOS code-signing team so `expo run:ios --device`
 * can sign without opening Xcode. The native `ios/` project is regenerated by
 * prebuild (it is gitignored), so this lives as a plugin to survive that.
 *
 * @param {import('@expo/config-plugins').ConfigPlugin<{ teamId: string }>} _
 */
const withDevelopmentTeam = (config, { teamId } = {}) => {
  if (!teamId) {
    throw new Error('withDevelopmentTeam: a `teamId` prop is required.');
  }

  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const configurations = project.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(configurations)) {
      const buildSettings = configurations[key].buildSettings;
      // Only the application target carries a bundle identifier; skip the
      // project-level and Pods configurations.
      if (!buildSettings || !buildSettings.PRODUCT_BUNDLE_IDENTIFIER) {
        continue;
      }

      buildSettings.DEVELOPMENT_TEAM = teamId;
      buildSettings.CODE_SIGN_STYLE = 'Automatic';
    }

    return config;
  });
};

module.exports = withDevelopmentTeam;
